version: '3'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - ./docs/create_shema_db.sql:/docker-entrypoint-initdb.d/create_shema_db.sql
    ports:
      - "5433:5432"
