"""New bd

Revision ID: 08904ad340ce
Revises: 549427b05af9
Create Date: 2024-06-22 21:00:17.516188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08904ad340ce'
down_revision: Union[str, None] = '549427b05af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('subscribed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscribed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'subscribed_id')
    )
    op.add_column('posts', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('file_path', sa.String(), nullable=False))
    op.create_foreign_key(None, 'posts', 'topics', ['topic_id'], ['id'])
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('second_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('nickname', sa.String(), nullable=False))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('banned_is', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.create_foreign_key(None, 'user', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'banned_is')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'second_name')
    op.drop_column('user', 'first_name')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'file_path')
    op.drop_column('posts', 'topic_id')
    op.drop_table('subscription')
    op.drop_table('topics')
    op.drop_table('roles')
    # ### end Alembic commands ###
