"""Topic nullable

Revision ID: 3a0a792ec731
Revises: cd1d957662af
Create Date: 2024-06-30 20:58:09.494947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0a792ec731'
down_revision: Union[str, None] = 'cd1d957662af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
