"""File nullable

Revision ID: b258114641d9
Revises: 3a0a792ec731
Create Date: 2024-06-30 21:00:24.165552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b258114641d9'
down_revision: Union[str, None] = '3a0a792ec731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
